### ISSUE TITLE
Save Data

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#77]
[Priority: 2]
[SP: 8]
As a user, i want to be able to save my data

**Comment by marouen-lamiri** [comment]
#### Task Breakdown:
- Research Different type of possible saving techniques (Database, save file ...) (2~3h)
- Discuss with team what are we expecting (save point, save from menu, auto-save) (.5h)
- Implementation (further breakdown needed, to be added later on)

**Comment by smileyWolf** [comment]
#### Discussion ... (Facebook)
##### Lamiri Marouen
hey everyone, i managed to create a simple save but i need now to know what we would like to save. What stats do we need to save? Do we need to keep the same map as the one previously generated? If so, do we need to keep track of the damage we did to the enemy?

##### Guillaume Fortin

well health and energy are technically a secondary stat
so you need to save level-strength, dex, endurance-wisdom, spirit, and wtv the last one is called

##### Lamiri Marouen

yea, it will be removed, i used it as a visual indicator that it worked
OK, so instead of health and energy, should be the stats Guillaume says

**Comment by smileyWolf** [comment]
#### Discussion ...
More specific stats are:

![primarystats](https://cloud.githubusercontent.com/assets/2501915/5610206/be42b828-9480-11e4-85e4-dcb162e50c41.png)

**Comment by smileyWolf** [comment]
#### Updated: Saving the primary stats https://github.com/marouen-lamiri/Second-Soul/commit/e10213d2affb3c69871f7ffe5d1b8b1a63d73118
I added a Log to display the save-process in the console:

![saveprimarystats](https://cloud.githubusercontent.com/assets/2501915/5675498/8f1e4afc-978d-11e4-8482-554c6ac06759.png)

**Comment by smileyWolf** [comment]
#### Black-Box Testing

**Comment by smileyWolf** [comment]
#### Demo Steps
1. 
2. 
3.

**Comment by smileyWolf** [comment]
#### ...

**Comment by Kishor0122** [comment]
Character stats (and level) and inventory items are correctly saved when game is closed. Signing off.
