### ISSUE TITLE
Jumping into a game

### ISSUE THREAD

**Issue by Emmanuel-Tsapekis** [marouen-lamiri/Second-Soul#94]
[Priority: 1]
[SP: 8]
As a Sorcerer, I would like to be able to jump into an existent game at any time.

**Comment by nico3865** [comment]
Discussion

The difficulty for this story is that the sorcerer is being referenced all across the codebase. When a client disconnects, all the references to the old sorcerer need to be updated to the new one. For this task a SorcererInstanceManager was created, which takes care of the swapping logic onClientConnect, while providing a .getSorcerer() that should be used across the code instead of .findObjectByType the sorcerer.

**Comment by nico3865** [comment]
#### Demo Steps
1. Open NetworkStartMenu scene in two game instances
2. Create a Fighter in one, and a Sorcerer in the other.
3. Press the Return key --> Verify it opens the chat box
4. Focus the chat textbox, write a message and press Return --> Verify that the message appears in the textarea, in both game instances (server and client)
5. Unfocus the chat and wait 6 seconds  --> Verify that the chat buttons and textbox disappear, only the textarea remains visible.

**Comment by nico3865** [comment]
#### Task Breakdown (actual):

(2h) --design and create SorcererInstanceManager
	swap function to be used when client connects
	get function to be used across the code
(0.5h) --replace all occurrences of .findObjectByType sorcerer with SorcererInstanceManager.getSorcerer()
(2h) remove player:
	//--server: swap them// NO! it screws up AI takover, why? it only works if I keep the old sorcerer.
	client: destroy sorcerer locally (rpc call)
logout:
	client: send rpc
	server: remove client. (...client: destroy locally (rpc call))
// connect for first time:
	normal -- fine
connect with server, with a sorcerer already in the client's game
	impossible, put check but should never happen
(4h) connect with no sorcerer, but we don't know if the sorcerer already has an AI sorcerer or not:
	--client: swap (network.instantiate)
	client: send rpc: tellServerToDetectAndKeepNewSorcerer
		it's a third version: 
			update method: it needs to wait for a second sorcerer to appear
			//make sure it's notMine
			make sure it's not the same reference.
			then swap them.
	server: swap with a potential one:

**Comment by nico3865** [comment]
#### Black Box Testing

##### NB: Do testing steps in order

| Tests # | Inputs | Expected Output | Status |
| --- | --- | --- | --- |
| 1. Connect players | Open StartScreen scene in two game instances. Create a Fighter in one, and a Sorcerer in the other | --> Verify that the game can be played in 2 player mode, as usual | Pass |
| 2. Remove Client | Then, in the server instance, click "Remove Client" (next to the chat window) | --> In the client instance, verify that the Menu screen reappears --> Back in the server instance, verify that the Sorcerer is now controlled by the AI (on the server instance) | Pass |
| 3. Reconnect Client | Then in the client instance, click "Connect as Client" and select a Room. | --> Verify that gameplay resumes normally in both instances (server's sorcerer is now controlled by client, and client can play as usual) | Pass |
| 4. Logout Client | Repeat step 2. and 3. but by clicking "Logout" in the client instance instead first, instead of clicking "Remove Client" | Observe identical effects as for steps 2 and 3 | Pass |

These issues have been retested: #87, #73, #92, #91, #78, #77, #64, #45 
Tests failed: None
Last edit: 09/04/2015
